replicaCount: 2

image:
  repository: kimytsc/kakaopay-devops-assignment
  pullPolicy: IfNotPresent
  tag: "2.1.0.BUILD-SNAPSHOT"

namespace: "default"

nameOverride: "application"

fullnameOverride: "petclinic"

environments:
  - name: SPRING_DATASOURCE_URL
    value: jdbc:mysql://mysql.default.svc.cluster.local/petclinic

podTerminationGracePeriodSeconds: 30

securityContext:
  runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "false"
  hosts:
    - host: kakaopay.petclinic.com
      paths: [/]
